import "@tiptap/core"; // Assicurati di importare il modulo prima
import { Editor, EditorContent } from "@tiptap/react";
import { useCallback, useEffect, useRef } from "react";
import styled from "styled-components";
import { Theme, getTheme } from "./extensions/theme";
import { FloatingMenu } from "./floatingMenu";
import { Search } from "./search";
import { useEditor } from "./useEditor";

declare module "@tiptap/core" {
  interface Commands<ReturnType> {
    active: {
      setCurrentTime: (start: number) => ReturnType;
      updateCurrentActive: ({
        currentWord,
      }: {
        currentWord: { start: number; end: number };
      }) => ReturnType;
    };
    observation: {
      addObservation: ({
        id,
        title,
        color,
      }: {
        id: number;
        title: string;
        color?: string;
      }) => ReturnType;
    };
  }
}

const EditorWrapper = styled.div`
  border: none;
  .ProseMirror {
    background: transparent;
    border: none;
    outline: none;
    padding: 0;
    min-height: 0;
  }

  .transcript-observation-handle {
    position: relative;
    display: inline-block;
    width: 0;
    height: 1.2em;
    vertical-align: text-bottom;
    cursor: col-resize;
    touch-action: none;
    user-select: none;
    z-index: 1;

    &::before {
      content: "";
      position: absolute;
      top: 0;
      bottom: 0;
      left: -1px;
      width: 2px;
      background: ${({ theme }) => theme.palette.blue[600]};
    }

    &::after {
      content: "";
      position: absolute;
      left: -4px;
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: ${({ theme }) => theme.palette.blue[600]};
    }
  }

  .transcript-observation-handle-start::after {
    top: -6px;
  }

  .transcript-observation-handle-end::after {
    bottom: -6px;
  }

  .transcript-observation-handle-hit-area {
    position: absolute;
    top: -8px;
    bottom: -8px;
    left: -8px;
    width: 16px;
  }

  .is-resizing-observation {
    cursor: col-resize;
    user-select: none;

    .transcript-observation-handle {
      pointer-events: none;
    }
  }
`;

const AIDisclaimer = styled.p`
  font-size: 12px;
  font-style: italic;
  color: ${({ theme }) => theme.palette.grey[500]};
  margin: 8px 0 0;
`;

const Transcript = ({ editor }: { editor: Editor }) => {
  const ref = useRef<HTMLDivElement>(null);

  const handleDragStart = useCallback((event: DragEvent) => {
    const selection = window.getSelection();
    if (selection && selection.toString()) {
      event.preventDefault();
    }
  }, []);

  useEffect(() => {
    const currentRef = ref.current;
    if (!currentRef) return;

    currentRef.addEventListener("dragstart", handleDragStart);

    return () => {
      currentRef.removeEventListener("dragstart", handleDragStart);
    };
  }, [handleDragStart]);

  if (!editor) return null;

  const theme = getTheme(editor);
  const SearchStyleWrapper = theme.options.searchStyleWrapper;

  return (
    <SearchStyleWrapper>
      <EditorWrapper>
        <EditorContent ref={ref} editor={editor} />
      </EditorWrapper>
      <AIDisclaimer>
        The transcription has been generated by AI, please review carefully
      </AIDisclaimer>
    </SearchStyleWrapper>
  );
};

Transcript.useEditor = useEditor;
Transcript.Search = Search;
Transcript.FloatingMenu = FloatingMenu;

export { Theme, Transcript };
export type {
  ObservationClickPayload,
  ObservationInfo,
  ObservationRange,
} from "./extensions/observationResize";
