import { ComponentMeta, Story } from "@storybook/react";
import { theme } from "../../theme";
import { BarChart } from ".";
import { BarChartProps } from "./_types";

const Template: Story<BarChartProps> = (args) => (
  <BarChart {...args} />
);

export const Default = Template.bind({});
Default.args = {
  width: 500,
  height: 300,
  data: [
    {
      country: "AD",
      "hot dog": 49,
      "hot dogColor": "hsl(204, 70%, 50%)",
      burger: 130,
      burgerColor: "hsl(6, 70%, 50%)",
      sandwich: 64,
      sandwichColor: "hsl(11, 70%, 50%)",
      kebab: 76,
      kebabColor: "hsl(292, 70%, 50%)",
      fries: 190,
      friesColor: "hsl(22, 70%, 50%)",
      donut: 81,
      donutColor: "hsl(203, 70%, 50%)",
    },
    {
      country: "AE",
      "hot dog": 35,
      "hot dogColor": "hsl(320, 70%, 50%)",
      burger: 68,
      burgerColor: "hsl(347, 70%, 50%)",
      sandwich: 85,
      sandwichColor: "hsl(228, 70%, 50%)",
      kebab: 119,
      kebabColor: "hsl(326, 70%, 50%)",
      fries: 114,
      friesColor: "hsl(64, 70%, 50%)",
      donut: 13,
      donutColor: "hsl(358, 70%, 50%)",
    },
    {
      country: "AF",
      "hot dog": 24,
      "hot dogColor": "hsl(20, 70%, 50%)",
      burger: 79,
      burgerColor: "hsl(130, 70%, 50%)",
      sandwich: 151,
      sandwichColor: "hsl(339, 70%, 50%)",
      kebab: 103,
      kebabColor: "hsl(188, 70%, 50%)",
      fries: 78,
      friesColor: "hsl(305, 70%, 50%)",
      donut: 134,
      donutColor: "hsl(318, 70%, 50%)",
    },
    {
      country: "AG",
      "hot dog": 1,
      "hot dogColor": "hsl(338, 70%, 50%)",
      burger: 10,
      burgerColor: "hsl(1, 70%, 50%)",
      sandwich: 2,
      sandwichColor: "hsl(95, 70%, 50%)",
      kebab: 100,
      kebabColor: "hsl(267, 70%, 50%)",
      fries: 155,
      friesColor: "hsl(237, 70%, 50%)",
      donut: 156,
      donutColor: "hsl(126, 70%, 50%)",
    },
    {
      country: "AI",
      "hot dog": 149,
      "hot dogColor": "hsl(203, 70%, 50%)",
      burger: 163,
      burgerColor: "hsl(68, 70%, 50%)",
      sandwich: 193,
      sandwichColor: "hsl(134, 70%, 50%)",
      kebab: 106,
      kebabColor: "hsl(343, 70%, 50%)",
      fries: 87,
      friesColor: "hsl(89, 70%, 50%)",
      donut: 143,
      donutColor: "hsl(251, 70%, 50%)",
    },
    {
      country: "AL",
      "hot dog": 49,
      "hot dogColor": "hsl(23, 70%, 50%)",
      burger: 181,
      burgerColor: "hsl(16, 70%, 50%)",
      sandwich: 153,
      sandwichColor: "hsl(330, 70%, 50%)",
      kebab: 43,
      kebabColor: "hsl(287, 70%, 50%)",
      fries: 107,
      friesColor: "hsl(111, 70%, 50%)",
      donut: 62,
      donutColor: "hsl(310, 70%, 50%)",
    },
    {
      country: "AM",
      "hot dog": 191,
      "hot dogColor": "hsl(43, 70%, 50%)",
      burger: 123,
      burgerColor: "hsl(34, 70%, 50%)",
      sandwich: 26,
      sandwichColor: "hsl(9, 70%, 50%)",
      kebab: 104,
      kebabColor: "hsl(315, 70%, 50%)",
      fries: 189,
      friesColor: "hsl(282, 70%, 50%)",
      donut: 51,
      donutColor: "hsl(165, 70%, 50%)",
    },
  ],
  keys: ["hot dog", "burger", "sandwich", "kebab", "fries", "donut"],
  indexBy: "country",
  margin: { top: 50, right: 130, bottom: 50, left: 60 },
  padding: 0.3,
  groupMode: "grouped",
  valueScale: { type: "linear" },
  indexScale: { type: "band", round: true },
  colors: { scheme: "blues" },
  theme: {
    textColor: theme.colors.primaryHue,
    fontFamily: theme.fonts.system,
  },
  axisBottom: {
    tickSize: 5,
    tickPadding: 5,
    tickRotation: 0,
    legend: "country",
    legendPosition: "middle",
    legendOffset: 32,
  },
  axisLeft: {
    tickSize: 5,
    tickPadding: 5,
    tickRotation: 0,
    legend: "food",
    legendPosition: "middle",
    legendOffset: -40,
  },
  labelSkipWidth: 12,
  labelSkipHeight: 12,
  labelTextColor: {
    from: "color",
    modifiers: [["darker", 1.6]],
  },
  legends: [
    {
      dataFrom: "keys",
      anchor: "bottom-right",
      direction: "column",
      justify: false,
      translateX: 120,
      translateY: 0,
      itemsSpacing: 2,
      itemWidth: 100,
      itemHeight: 20,
      itemDirection: "left-to-right",
      itemOpacity: 0.85,
      symbolSize: 20,
      effects: [
        {
          on: "hover",
          style: {
            itemOpacity: 1,
          },
        },
      ],
    },
  ],
};

export default {
  title: "Charts/BarChart",
  component: BarChart,
} as ComponentMeta<typeof BarChart>;
